name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: make sync
      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      LOGFIRE_TOKEN=placeholder
      MCP_SERVER_URL=http://localhost:9000
      MISTRAL_API_KEY=placeholder
      TEMPORAL_SERVER_URL=localhost:7233
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: make sync
      - name: Run tests
        run: make tests